const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const trMonths=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>iso(new Date());
const fromIso=s=>{const [y,m,d]=String(s||today()).split('-').map(Number);return new Date(y,m-1,d)};
const niceDate=s=>{const d=fromIso(s);return `${d.getDate()} ${trMonths[d.getMonth()]} ${d.getFullYear()}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attr=esc;
const navItems=[['home','✦','Keşif'],['tarot','◈','Tarot'],['library','✶','Kart Atlası'],['sky','☽','Gökyüzü'],['lunar','◐','Ay takvimi'],['natal','✷','Doğum haritası'],['calculator','◇','Astro hesaplar'],['compare','♡','Uyum haritası'],['readings','▤','Okumalar'],['account','♙','Hesabım'],['settings','⚙','Ayarlar']];
const themes=[{id:'blue',name:'Gece Atlası',description:'Lacivert gök · altın yıldızlar',image:'./landscape-blue-hd.png'},{id:'red',name:'Kızıl Tutulma',description:'Kızıl ay · kehribar parıltı',image:'./landscape-red-hd.png'},{id:'green',name:'Zümrüt Kehanet',description:'Yeşil vadi · mistik ışık',image:'./landscape-green-hd.png'}];
const state={items:[],settings:{},view:'home'};
const api=async(path,body)=>window.localApi(path,body);
const live=kind=>state.items.filter(item=>item.kind===kind&&!item.deleted);
function applyTheme(){document.body.dataset.theme=themes.some(t=>t.id===state.settings.theme)?state.settings.theme:'blue';document.body.dataset.starDensity=state.settings.star_density||1;document.body.classList.toggle('motion-off',state.settings.motion===false);window.updateStarfield?.()}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3500)}
async function save(kind,data,id){const {item}=await api('item',{kind,data,id});const i=state.items.findIndex(x=>x.id===item.id);if(i<0)state.items.push(item);else state.items[i]=item;render();return item}
async function remove(id){await api('delete',{id});state.items=state.items.filter(x=>x.id!==id);render()}
function empty(message){return `<div class='empty'><span>✧</span><p>${esc(message)}</p></div>`}
function header(eyebrow,title,description='',tools=''){return `<section class='page-head'><div class='page-head-orbit' aria-hidden='true'></div><div class='page-head-copy'><div class='eyebrow'>${eyebrow}</div><h1 class='page-title'>${title}</h1>${description?`<p class='page-sub'>${description}</p>`:''}</div>${tools?`<div class='head-tools'>${tools}</div>`:''}</section>`}
function renderHome(){const points=skyAt(new Date()),phase=moonPhase(points);return `<div class='home-hero'><div class='hero-sky' aria-hidden='true'><span class='hero-moon'></span><span class='hero-orbit orbit-one'></span><span class='hero-orbit orbit-two'></span></div><div class='hero-copy'><span class='eyebrow'>AY ATLASI / GÖKYÜZÜNE AÇILAN KAPI</span><h1>Gökyüzü bir harita.<br><em>Kartlar bir kapı.</em></h1><p>Bir soruyla başla. Üç kart çek. Sonra doğduğun anın göğünü keşfet.</p><div class='hero-actions'><button class='primary-btn' data-nav='tarot'>✦ Tarot okumaya başla</button><button class='soft-btn' data-nav='natal'>✷ Haritamı çıkar</button></div></div><div class='hero-cards' aria-hidden='true'><img class='hero-card hero-card-one' src='./tarot-art/17_Star.jpg' alt=''><img class='hero-card hero-card-two' src='./tarot-art/18_Moon.jpg' alt=''><img class='hero-card hero-card-three' src='./tarot-art/19_Sun.jpg' alt=''></div></div><div class='home-stats'><div><span>BUGÜNÜN GÜNEŞİ</span><strong>${signText(points[0].lon)}</strong></div><div><span>AYIN EVRESİ</span><strong>${phase.name}</strong></div><div><span>BUGÜNÜN AYI</span><strong>${signText(points[1].lon)}</strong></div><button data-nav='sky'>Gökyüzünü incele <b>↗</b></button></div><div class='home-grid'><button class='home-feature' data-nav='tarot'><span class='feature-number'>01 / KART ODASI</span><span class='feature-glyph'>◈</span><strong>Kartların hikâyesi</strong><small>Klasik okuma veya yorumcu masası. Sorunu yaz, karmayı durdur, üç kartını seç.</small><span class='feature-link'>Masaya geç ↗</span></button><button class='home-feature' data-nav='natal'><span class='feature-number'>02 / DOĞUM GÖĞÜ</span><span class='feature-glyph'>✷</span><strong>Doğduğun an</strong><small>Gezegenler, yükselen, evler ve açılar. Tarih, saat ve konumunla haritanı oluştur.</small><span class='feature-link'>Haritanı aç ↗</span></button></div><p class='source-note'>Kart resimleri Pamela Colman Smith’in 1909 Rider–Waite–Smith destesinin kamu malı taramalarındandır.</p>`}
function renderSettings(){const current=state.settings.theme||'blue';return `${header('KİŞİSEL ALAN','Ayarlar ✧','Görünümü seç, doğum haritanı ve okumalarını yedekle.')}<div class='card pad'><h2 class='card-title'>Gök paleti</h2><div class='theme-options'>${themes.map(t=>`<button class='theme-choice ${current===t.id?'active':''}' data-theme-choice='${t.id}' aria-pressed='${current===t.id}'><span class='theme-preview' style='background-image:url(${t.image})'></span><strong>${t.name}</strong><small>${t.description}</small></button>`).join('')}</div><label class='motion-setting'><input id='motionToggle' type='checkbox' ${state.settings.motion===false?'':'checked'}> Gökyüzü animasyonları açık</label></div><div class='settings-grid'><div class='card pad'><h2 class='card-title'>Verilerim</h2><p>Doğum bilgilerin ve tarot okumaların bu tarayıcıda saklanır. Başka cihazda kullanmak için yedek dosyanı aktarabilirsin.</p><div class='setting-actions'><button class='soft-btn' id='exportBtn'>↓ Yedeği indir</button><button class='soft-btn' id='importBtn'>↑ Yedek yükle</button><input id='importFile' type='file' accept='.json,application/json' hidden></div></div><div class='card pad'><h2 class='card-title'>Kaynak ve gizlilik</h2><p>Kartlar: Pamela Colman Smith, Rider–Waite–Smith (1909). Astronomik hesap: Astronomy Engine. Doğum yeri araması Open-Meteo ile yapılır.</p><p>Bu sürümde üyelik ve cihazlar arası eşitleme yoktur; kaydettiğin bilgiler GitHub deposuna gönderilmez.</p></div></div>`}
function renderNav(){$('#nav').innerHTML=navItems.map(([id,icon,label])=>`<button class='nav-item ${state.view===id?'active':''}' data-nav='${id}'><span class='nav-glyph'>${icon}</span><span>${label}</span></button>`).join('')}
function render(){applyTheme();renderNav();$('#breadcrumb').textContent=navItems.find(x=>x[0]===state.view)?.[2]||'Keşif';$('#todayPill').textContent=niceDate(today());const views={home:renderHome,tarot:renderTarot,library:renderLibrary,sky:renderSky,lunar:renderLunar,natal:renderNatal,calculator:renderCalculator,compare:renderCompare,readings:renderReadings,account:renderAccount,settings:renderSettings};$('#content').innerHTML=`<div class='content-inner'>${views[state.view]()}</div>`;bindMysticView();bindSettingsView();bindFeaturesView()}
function navigate(view){state.view=view;render();window.scrollTo({top:0,behavior:'smooth'});$('#content').scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',event=>{const target=event.target.closest('[data-nav]');if(target){navigate(target.dataset.nav);return}const theme=event.target.closest('[data-theme-choice]');if(theme){api('settings',{theme:theme.dataset.themeChoice}).then(({settings})=>{state.settings=settings;render()});return}});
$('#settingsBtn').addEventListener('click',()=>navigate('settings'));
$('#themeBtn').addEventListener('click',()=>{const i=themes.findIndex(t=>t.id===state.settings.theme);api('settings',{theme:themes[(i+1)%themes.length].id}).then(({settings})=>{state.settings=settings;render()})});
function bindSettingsView(){
  $('#motionToggle')?.addEventListener('change',event=>api('settings',{motion:event.target.checked}).then(({settings})=>{state.settings=settings;render()}));
  $('#exportBtn')?.addEventListener('click',async()=>{try{const data=await api('export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ay-atlasi-yedek-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Yedek indirildi')}catch(error){toast(error.message)}});
  $('#importBtn')?.addEventListener('click',()=>$('#importFile').click());
  $('#importFile')?.addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());await api('import',data);state.items=(await api('items')).items;state.settings=(await api('settings')).settings;render();toast('Yedek içe aktarıldı')}catch(error){toast(error.message)}})
}
async function init(){try{state.items=(await api('items')).items;state.settings=(await api('settings')).settings;render()}catch(error){$('#content').innerHTML=empty('Uygulama başlatılamadı: '+error.message)}}
window.refreshAyState=init;
