/* Ay Atlası: keşif, kişiselleştirme ve ek astroloji araçları. */
const featureState={libraryGroup:'Tümü',libraryQuery:'',libraryCard:null,compare:null,compareCityResults:[]};
const namesOfGroups=['Tümü','Büyük Arkana',...suitData.map(x=>x[0])];
function renderLibrary(){
 const cards=deck.filter(c=>(featureState.libraryGroup==='Tümü'||c.group===featureState.libraryGroup)&&(`${c.name} ${c.group} ${c.meaning}`).toLocaleLowerCase('tr-TR').includes(featureState.libraryQuery.toLocaleLowerCase('tr-TR')));
 return `${header('78 KART / ÖZGÜN GÖRSELLER','Kart Atlası ✶','Rider–Waite–Smith destesini kendi hızında keşfet. Kartlar düz konumda anlatılır.')}<div class="card pad atlas-controls"><div class="form-field"><label for="atlasSearch">Kart ara</label><input id="atlasSearch" type="search" value="${attr(featureState.libraryQuery)}" placeholder="Örneğin Ay, Kupa, cesaret…"></div><div class="atlas-filters">${namesOfGroups.map(g=>`<button class="mini-btn ${featureState.libraryGroup===g?'active':''}" data-atlas-group="${attr(g)}">${esc(g)}</button>`).join('')}</div></div><div id="atlasCards" class="atlas-grid">${cards.map(c=>`<button class="atlas-card" data-atlas-card="${c.id}" aria-label="${attr(c.name)} kartını aç"><img src="${attr(c.image)}" alt="${attr(c.name)}" loading="lazy"><span>${esc(c.name)}</span></button>`).join('')||empty('Aramana uygun kart bulunamadı.')}</div>${featureState.libraryCard?renderCardDetail(featureState.libraryCard):''}`;
}
function renderCardDetail(id){const c=deck.find(x=>x.id===id);if(!c)return '';const s=suitData.find(x=>x[0]===c.group);return `<div class="atlas-overlay" data-close-card="1"><article class="atlas-detail card pad" role="dialog" aria-modal="true" aria-label="${attr(c.name)}"><button class="mini-btn atlas-close" data-close-card="1">Kapat ×</button><img src="${attr(c.image)}" alt="${attr(c.name)} · özgün Rider–Waite–Smith kartı"><div><div class="eyebrow">${esc(c.group)} · ${esc(c.number)}</div><h2>${esc(c.name)}</h2><p>${esc(c.meaning)}</p>${s?`<p><b>${esc(s[2].toLocaleUpperCase('tr-TR'))} ELEMENTİ</b> · ${esc(s[3])}</p>`:'<p><b>BÜYÜK ARKANA</b> · yaşam döngüsünün önemli eşikleri</p>'}<p class="hint">Kendine sor: Bu kartın hangi simgesi bugünkü durumuna dokunuyor?</p><button class="primary-btn" data-nav="tarot">Bir okumada dene ↗</button></div></article></div>`}
function lunarDays(){const now=new Date(),days=[];for(let i=0;i<30;i++){const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()+i,12),p=skyAt(d),m=moonPhase(p);days.push({date:d,phase:m,sign:signs[signIndex(p[1].lon)]})}return days}
function renderLunar(){const days=lunarDays(),current=days[0];return `${header('AYIN RİTMİ','Ay Takvimi ◐','Önümüzdeki 30 günün Ay evresi, aydınlanma oranı ve burcu.')}<div class="moon-overview card pad"><div class="moon-visual" style="--illum:${current.phase.illumination}%">☾</div><div><div class="eyebrow">BUGÜNÜN AYI</div><h2>${current.phase.name}</h2><p>${current.sign[1]} ${current.sign[0]} · yaklaşık %${current.phase.illumination} aydınlık</p><p class="hint">Ay evresi Güneş ve Ay ekliptik boylamlarının açısına göre yaklaşık hesaplanır. Tarihler yerel öğlen içindir.</p></div></div><div class="lunar-grid">${days.map(({date,phase,sign},i)=>`<div class="card lunar-day ${i===0?'today':''}"><small>${i===0?'BUGÜN':date.toLocaleDateString('tr-TR',{weekday:'short'}).toLocaleUpperCase('tr-TR')}</small><b>${date.toLocaleDateString('tr-TR',{day:'numeric',month:'long'})}</b><strong>${phase.name}</strong><span>${sign[1]} ${sign[0]} · %${phase.illumination}</span></div>`).join('')}</div>`}
function renderCompare(){const own=profileItem(),v=featureState.compare;let results='';if(v&&own){try{const a=buildChart(own.data),b=buildChart(v),focus=['Sun','Moon','Mercury','Venus','Mars'],pairs=[];for(const p of a.points.filter(x=>focus.includes(x.key)))for(const q of b.points.filter(x=>focus.includes(x.key))){const angle=angleDiff(p.lon,q.lon);for(const [name,exact,orb,meaning] of aspectTypes)if(Math.abs(angle-exact)<=Math.min(orb,4)){pairs.push({p,q,name,orb:Math.abs(angle-exact),meaning});break}}pairs.sort((x,y)=>x.orb-y.orb);results=`<div class="card pad compare-results"><div class="eyebrow">İKİ HARİTA / TEMAS NOKTALARI</div><h2>${esc(own.data.name||'Sen')} & ${esc(v.name||'Diğer kişi')}</h2><div class="compare-big"><span>☉ ${signs[signIndex(a.points[0].lon)][0]} / ${signs[signIndex(b.points[0].lon)][0]}</span><span>☽ ${signs[signIndex(a.points[1].lon)][0]} / ${signs[signIndex(b.points[1].lon)][0]}</span><span>♀ ${signs[signIndex(a.points[3].lon)][0]} / ${signs[signIndex(b.points[3].lon)][0]}</span></div><p class="hint">Açılar iki kişinin seçili gezegenleri arasındaki geometrik temaslardır; ilişki kalitesine puan veya kesin hüküm vermez.</p><div class="aspects-grid">${pairs.slice(0,16).map(x=>`<div class="aspect-item"><b>${esc(x.p.name)} · ${x.name} · ${esc(x.q.name)}</b><small>${x.orb.toFixed(1)}° orb</small><p>${esc(x.p.domain)} ile ${esc(x.q.domain)} arasında ${x.meaning}.</p></div>`).join('')||'<p>4° orb içinde ana açı bulunamadı.</p>'}</div></div>`}catch(e){results=`<div class="card pad error-text">${esc(e.message)}</div>`}}
 return `${header('İKİ GÖKYÜZÜ','Uyum haritası ♡','İki doğum haritasının seçili gezegen açılarını birlikte incele.')}<div class="card pad compare-form"><h2 class="card-title">İkinci kişinin doğum bilgileri</h2>${own?`<p class="hint">İlk harita: ${esc(own.data.name||'Kaydedilmiş haritan')}. İkinci kişinin bilgileri yalnızca bu oturumda kullanılır.</p>`:`<p>Önce kendi doğum haritanı oluştur.</p><button class="primary-btn" data-nav="natal">Haritama git</button>`}<form id="compareForm"><div class="form-row"><div class="form-field"><label>Ad</label><input name="name" value="${attr(v?.name||'')}" placeholder="İsteğe bağlı"></div><div class="form-field"><label>Doğum yeri</label><div class="city-search"><input name="city" id="compareCity" value="${attr(v?.city||'')}" placeholder="Şehir ara"><button id="compareCitySearch" type="button" class="soft-btn">Ara</button></div><div id="compareCityResults" class="city-results"></div></div></div><div class="form-row"><div class="form-field"><label>Tarih</label><input type="date" name="date" required value="${attr(v?.date||'')}"></div><div class="form-field"><label>Saat</label><input type="time" name="time" required value="${attr(v?.time||'12:00')}"></div></div><div class="form-row"><div class="form-field"><label>Enlem</label><input type="number" step="any" min="-89" max="89" name="latitude" required value="${attr(v?.latitude??'')}"></div><div class="form-field"><label>Boylam</label><input type="number" step="any" min="-180" max="180" name="longitude" required value="${attr(v?.longitude??'')}"></div></div><div class="form-field"><label>Saat dilimi (IANA)</label><input name="timezone" required value="${attr(v?.timezone||'Europe/Istanbul')}"></div><button class="primary-btn" type="submit" ${own?'':'disabled'}>✧ Haritaları karşılaştır</button></form></div>${results}`;
}
const oldHome=renderHome;renderHome=function(){const name=state.settings.display_name?.trim(),daily=live('daily_card').find(x=>x.data.date===today()),c=daily&&deck.find(x=>x.id===daily.data.card);return `${oldHome()}<div class="personal-grid"><div class="card pad"><div class="eyebrow">SANA ÖZEL</div><h2>${name?`Merhaba, ${esc(name)} ✧`:'Kendi göğünü adlandır ✧'}</h2><p>${name?'Ay Atlası bugün de seninle.':'Ayarlardan adını yaz; bu alan senin adına açılsın.'}</p><button class="link-btn" data-nav="settings">Kişiselleştir ↗</button></div><div class="card pad daily-card"><div class="eyebrow">GÜNÜN KARTI</div>${c?`<img src="${attr(c.image)}" alt="${attr(c.name)}"><div><h2>${esc(c.name)}</h2><p>${esc(c.meaning)}</p><small>Bu kart yalnızca bugün için seçildi.</small></div>`:`<div><h2>Bugünün simgesini aç</h2><p>78 özgün kart arasından bir kart çek.</p><button class="primary-btn" data-daily-card="1">✦ Kartımı çek</button></div>`}</div></div>`};
const oldSky=renderSky;renderSky=function(){const base=oldSky(),date=fromIso(mystic.transitDate);date.setHours(12);const current=skyAt(date),before=new Date(date.getTime()-86400000),after=new Date(date.getTime()+86400000);const rows=current.slice(2).map(p=>{const prev=astronomyPosition(p.key,before),next=astronomyPosition(p.key,after),speed=((next-prev+540)%360)-180;return `<div class="motion-item"><b>${p.symbol} ${p.name}</b><span>${speed<-.015?'℞ Retro':Math.abs(speed)<.015?'◌ Durağan':'→ İleri'} · ${Math.abs(speed).toFixed(2)}°/gün</span></div>`});const aspects=natalAspects(current).slice(0,9);return `${base}<div class="two-col section-space"><div class="card pad"><h2 class="card-title">↗ Gezegen hareketleri</h2><div class="motion-grid">${rows.join('')}</div><p class="hint">Günlük ekliptik boylam farkı; durağan eşiği yaklaşık 0,015°/gün.</p></div><div class="card pad"><h2 class="card-title">✶ Güncel açılar</h2>${aspects.map(a=>`<div class="transit-line">${a.a.symbol} ${a.a.name} · ${a.name} · ${a.b.symbol} ${a.b.name} <b>${a.orb.toFixed(1)}°</b></div>`).join('')||'<p class="hint">Yakın büyük açı bulunamadı.</p>'}</div></div>`};
const oldTarot=renderTarot;renderTarot=function(){let html=oldTarot();if(mystic.revealed)html=html.replace('</div></div><aside class="tarot-aside">',`<div class="card pad personal-note"><label for="tarotNote">Kendi yorumun / hissettiğin simgeler</label><textarea id="tarotNote" maxlength="2000" placeholder="Bu üç kart sana ne anlatıyor?">${esc(mystic.note||'')}</textarea><p class="hint">Okumayı kaydettiğinde bu not da cihazında saklanır.</p></div></div><aside class="tarot-aside">`);return html};
renderReadings=function(){const readings=live('tarot_reading').sort((a,b)=>b.updated-a.updated);return `${header('KART GÜNLÜĞÜ','Okuma defteri ▤','Sorduğun sorulara, kartlarına ve kendi notlarına geri dön.')}<div class="readings-grid">${readings.length?readings.map(x=>`<article class="card pad saved-reading"><div class="eyebrow">${x.data.mode==='reader'?'YORUMCU MASASI':'KLASİK OKUMA'} · ${new Date(x.updated*1000).toLocaleDateString('tr-TR')}</div><h2>${esc(x.data.question||'Sorulmamış bir soru')}</h2><div class="saved-card-art">${(x.data.cards||[]).map(id=>{const c=deck.find(y=>y.id===id);return c?`<div><img src="${attr(c.image)}" alt="${attr(c.name)}" loading="lazy"><span>${esc(c.name)}</span></div>`:''}).join('')}</div>${x.data.note?`<p class="reading-memory">“${esc(x.data.note)}”</p>`:''}<button class="mini-btn" data-delete-reading="${attr(x.id)}">Kaydı sil</button></article>`).join(''):empty('Henüz kaydedilmiş okuma yok. İlk kartlarını çekebilirsin.')}</div>`};
const oldSettings=renderSettings;renderSettings=function(){return `${oldSettings()}<div class="card pad personal-settings"><div class="eyebrow">KENDİ ATLASIN</div><h2 class="card-title">Kişiselleştir</h2><div class="form-row"><div class="form-field"><label for="displayName">Sana nasıl seslenelim?</label><input id="displayName" maxlength="40" value="${attr(state.settings.display_name||'')}" placeholder="Adın veya takma adın"></div><div class="form-field"><label for="starDensity">Yıldız yoğunluğu <output id="densityValue">${Math.round((state.settings.star_density||1)*100)}%</output></label><input id="starDensity" type="range" min="0.35" max="1.6" step="0.05" value="${state.settings.star_density||1}"></div></div><p class="hint">Bu tercihler yalnızca kullandığın tarayıcıda saklanır.</p></div>`};
const oldNatal=renderNatal;renderNatal=function(){let html=oldNatal();const p=profileItem();if(!p)return html;try{const c=buildChart(p.data),counts={Öncü:0,Sabit:0,Değişken:0};c.points.slice(0,7).forEach(x=>counts[signs[signIndex(x.lon)][3]]++);html+=`<div class="card pad natal-signature"><div class="eyebrow">HARİTA İMZASI</div><h2 class="card-title">Nitelik dengesi</h2><div class="signature-grid">${Object.entries(counts).map(([k,n])=>`<div><strong>${n}</strong><span>${k}</span></div>`).join('')}</div><p class="hint">Güneş, Ay, Merkür, Venüs, Mars, Jüpiter ve Satürn yerleşimlerinden sayılır.</p></div>`}catch(_){}return html};
function bindFeaturesView(){
 $('#atlasSearch')?.addEventListener('input',e=>{featureState.libraryQuery=e.target.value;const pos=e.target.selectionStart;render();$('#atlasSearch')?.focus();$('#atlasSearch')?.setSelectionRange(pos,pos)});
 $('#tarotNote')?.addEventListener('input',e=>{mystic.note=e.target.value});
 $('#displayName')?.addEventListener('change',async e=>{const {settings}=await api('settings',{display_name:e.target.value.trim()});state.settings=settings;toast('Adın kaydedildi ✧')});
 $('#starDensity')?.addEventListener('input',e=>{$('#densityValue').textContent=`${Math.round(Number(e.target.value)*100)}%`;document.body.dataset.starDensity=e.target.value;window.updateStarfield?.()});
 $('#starDensity')?.addEventListener('change',async e=>{const {settings}=await api('settings',{star_density:Number(e.target.value)});state.settings=settings});
 $('#compareForm')?.addEventListener('submit',e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.target));v.latitude=Number(v.latitude);v.longitude=Number(v.longitude);buildChart(v);featureState.compare=v;render()}catch(error){toast(error.message)}});
 $('#compareCitySearch')?.addEventListener('click',async()=>{const q=$('#compareCity').value.trim(),out=$('#compareCityResults');if(q.length<2){toast('En az iki harf yaz');return}out.textContent='Şehir aranıyor…';try{const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=7&language=tr&format=json`);if(!response.ok)throw Error('Şehir araması kullanılamıyor');featureState.compareCityResults=(await response.json()).results||[];out.innerHTML=featureState.compareCityResults.map((x,i)=>`<button type="button" class="city-option" data-compare-city="${i}">${esc(x.name)}, ${esc(x.country||'')}</button>`).join('')||'Sonuç bulunamadı'}catch(error){out.textContent=error.message}});
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-atlas-group],[data-atlas-card],[data-close-card],[data-daily-card],[data-compare-city]');if(!b)return;
 if(b.dataset.atlasGroup){featureState.libraryGroup=b.dataset.atlasGroup;render()}
 else if(b.dataset.atlasCard){featureState.libraryCard=b.dataset.atlasCard;render();$('.atlas-overlay')?.scrollIntoView({block:'center'})}
 else if(b.dataset.closeCard){if(e.target!==b&&e.target.closest('.atlas-detail')&&!e.target.closest('.atlas-close'))return;featureState.libraryCard=null;render()}
 else if(b.dataset.dailyCard){const buf=new Uint32Array(1);crypto.getRandomValues(buf);await save('daily_card',{date:today(),card:deck[buf[0]%deck.length].id})}
 else if(b.dataset.compareCity){const x=featureState.compareCityResults[Number(b.dataset.compareCity)],f=$('#compareForm');if(!x||!f)return;f.elements.city.value=`${x.name}, ${x.country||''}`;f.elements.latitude.value=x.latitude;f.elements.longitude.value=x.longitude;f.elements.timezone.value=x.timezone||'UTC';$('#compareCityResults').innerHTML=''}
});
init();
